# Generated by Django 4.2.1 on 2023-05-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KLC_App', '0002_role_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='user/'),
        ),
    ]
